version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    # volumes:
    #   - .:/app
    command: ["npm", "start"]
